name: Packaging (Debian, Windows and macOS)

on: [push, pull_request]

jobs:

  windows:
    runs-on: windows-2016
    strategy:
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64, gtk: 3 },
          { msystem: MINGW32, arch: i686, gtk: 3 }
        ]
    defaults:
      run:
        shell: msys2 {0}
    env:
      ARCH: ${{ matrix.arch }}
      NICOTINE_GTK_VERSION: ${{ matrix.gtk }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true

      - name: Install build dependencies
        run: |
          packaging/windows/dependencies-core.sh
          packaging/windows/dependencies-packaging.sh

      - name: Build installer
        run: |
          pyinstaller packaging/windows/nicotine.spec
          packaging/windows/create-installer.sh
          mkdir installer
          cp -r packaging/windows/Nicotine*.exe installer/

      - name: Archive installer artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-${{ matrix.arch }}-installer
          path: installer

      - name: Archive package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-${{ matrix.arch }}-package
          path: dist